[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = [ "*/cache/**", "*/custom/themes/powerlevel10k"]
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
    exact = true
    stripComponents = 1
[".tmux/plugins/tpm"]
    type ="archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/tags/v3.0.0.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
