require("symbols-outline").setup({
    highlight_hovered_item = true,
    symbols = {
        File = { icon = "" },
        Module = { icon = "" },
        Namespace = { icon = "" },
        Package = { icon = "" },
        Class = { icon = "" },
        Method = { icon = "" },
        Property = { icon = "" },
        Field = { icon = "" },
        Constructor = { icon = "" },
        Enum = { icon = "" },
        Interface = { icon = "ﰮ" },
        Function = { icon = "" },
        Variable = { icon = "" },
        Constant = { icon = "" },
        String = { icon = "" },
        Number = { icon = "" },
        Boolean = { icon = "⊨" },
        Array = { icon = "" },
        Object = { icon = "⦿" },
        Key = { icon = "" },
        Null = { icon = "ﳠ" },
        EnumMember = { icon = "" },
        Struct = { icon = "" },
        Event = { icon = "" },
        Operator = { icon = "+" },
        TypeParameter = { icon = "" },
        Component = { icon = "" },
        Fragment = { icon = "" },
    },
})
